# This is the network config written by 'subiquity'
network:
  ethernets:
    ens160:
      addresses:
       - 172.16.50.3/29
      gateway4: 172.16.50.2
      nameservers:
        addresses: [172.16.50.2]
  version: 2
